### ISSUE TITLE
"es-theme-switch" show battery percentage

### ISSUE THREAD

**Issue by xclover0** [Jetup13/Emulationstation-OGA-Theme-Gallery#6]
hello, possible to show battery icon and battery percentage of this theme? https://github.com/Jetup13/es-theme-switch
thank you

**Comment by Jetup13** [comment]
Yes the battery icon can be shown but it depends on the emulationstation version used. I never touched it from the default because supporting another icon on screen for 4 to 5 different devices gets difficult and hectic.  

You can edit it yourself:

The line in the [theme.xml](https://github.com/Jetup13/es-theme-switch/blob/master/theme.xml#L138) file. 

And the [battery theme options](https://github.com/batocera-linux/batocera-emulationstation/blob/master/es-core/src/ThemeData.cpp#L337) that can be used (if supported with the certain emulationstation used)
